apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:            # 这里定义的是 Deployment 的 spec 
  selector:
    matchLabels:
      app: nginx
  replicas: 3    # deployment 用 replica set 来管理 pods 的副本
  template:
    metadata:
      labels:
        app: nginx
    spec:        # 这里定义的是 Pod 的 spec
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          limits:                  # 定义对容器的资源限制
            cpu: "0.1"
            memory: "128Mi"

